version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '17:00'
      timezone: 'Europe/Warsaw'
    cooldown:
      semver-patch-days: 7
      semver-minor-days: 14
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    versioning-strategy: increase
